#SUBCONSULTAS
/*SON CONSULTAS QUE SE EJECUTAN DENTRO DE OTRAS
CONSISTEN EN UTILIZAR LOS RESULTADOS DE LA SUBCONSULTA
PARA OPERAR EN LA CONSULTA PRINCIPAL*/
INSERT INTO usuarios VALUES(null,"admin","admin","admin@admin","123",CURDATE());
#SACÁR TODOS LOS USUARIOS CON ENTRADAS
SELECT * FROM usuarios WHERE id IN (SELECT usuario_id FROM entradas);
SELECT * FROM usuarios WHERE id NOT IN (SELECT usuario_id FROM entradas);

SELECT * FROM usuarios WHERE id 
IN(SELECT usuario_id FROM entradas WHERE titulo LIKE '%petro%');

#SACAR TODAS LAS ENTRADAS DE LA CATEGORIA ACCION USANDO SU NOMBRE#
SELECT * FROM entradas WHERE categoria_id
IN(SELECT id FROM categorias WHERE nombre='Romance');

#MOSTRAR LAS CATEGORIAS CON MAS DE 3 ENTRADAS
SELECT * FROM categorias WHERE 
   (SELECT categoria_id FROM entradas 
   HAVING COUNT(categoria_id) >= 3);

#MOSTRAR LOS USUARIOS QUE CREARON UNA ENTRADA UN MARTES


#MOSTRAR EL NOMBRE DEL USUARIO QUE TENGA MAS ENTRADAS
#EL IGUAL SE USA CUANDO SOLO VA DEVOLVER UN REGISTRO
SELECT nombre FROM usuarios WHERE id=(
   SELECT usuario_id FROM entradas
   GROUP BY usuario_id
   ORDER BY COUNT(usuario_id) DESC
   LIMIT 1
);

#MOSTRAR LAS CATEGORIAS SIN ENTRADAS
SELECT id FROM categorias 
WHERE id NOT IN(
   SELECT categoria_id FROM entradas
);